# Generated by Django 4.1.4 on 2022-12-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0013_remove_timetable_slot_course_and_teacher_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable_Slot',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednseday'), ('Thursday', 'Thurdasy'), ('Firday', 'Friday')], default='Monday', max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_and_teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.course_and_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('lab_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.lab')),
                ('room_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.room')),
            ],
        ),
    ]
