# Generated by Django 4.1.4 on 2022-12-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('department_name', models.CharField(max_length=200)),
                ('current_sms', models.CharField(max_length=200)),
                ('total_student', models.IntegerField()),
                ('total_room', models.IntegerField()),
                ('total_labs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('lab_name', models.CharField(max_length=200)),
                ('total_seats', models.IntegerField()),
                ('is_smart_lab', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('room_name', models.CharField(max_length=200)),
                ('total_seats', models.IntegerField()),
                ('is_smart_room', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
