# Generated by Django 4.1.4 on 2022-12-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departments_labs_rooms_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='current_sms',
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('have_freezing_slot', models.BooleanField(default=False)),
                ('freezing_slot_start', models.TimeField()),
                ('freezing_slot_end', models.TimeField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('sub_department_name', models.CharField(max_length=200)),
                ('current_available_sms', models.CharField(max_length=200)),
                ('total_student', models.IntegerField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Samester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('samester_name', models.CharField(max_length=200)),
                ('classes_per_week', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('sub_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.sub_departments')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credits_hourse', models.IntegerField()),
                ('classes_per_week', models.IntegerField()),
                ('have_labs', models.BooleanField(default=False)),
                ('sub_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.sub_departments')),
                ('teacher', models.ManyToManyField(to='departments.teachers')),
            ],
        ),
    ]
