# Generated by Django 4.1.4 on 2022-12-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_remove_departments_current_sms_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationForm',
            fields=[
                ('roll_number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=200)),
                ('student_strength', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequest',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credits_hourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('program_name', models.CharField(max_length=200)),
                ('currently_available_sms', models.CharField(max_length=200)),
                ('total_students', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='lab_name',
            new_name='block_name',
        ),
        migrations.RenameField(
            model_name='labs',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='room_name',
            new_name='block_name',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='samester',
            old_name='samester_name',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='samester',
            old_name='classes_per_week',
            new_name='student_strength',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sub_department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='code',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='code',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='id',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='sub_department',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='samester_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.samester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='short_name',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labs',
            name='short_name',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='short_name',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samester',
            name='short_name',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='additional_duties',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='designation',
            field=models.CharField(choices=[('Leacturer', 'Leacturer'), ('Assistante_Professor', 'Assistante Professor'), ('Associate_Prfessor', 'Associate Prfessor'), ('Professor', 'Professor')], default='Leacturer', max_length=200),
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacher_id',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacher_qulification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Sub_Departments',
        ),
        migrations.AddField(
            model_name='program',
            name='department_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.departments'),
        ),
        migrations.AddField(
            model_name='allocationform',
            name='courses_ids',
            field=models.ManyToManyField(to='departments.course'),
        ),
        migrations.AddField(
            model_name='allocationform',
            name='program_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.program'),
        ),
        migrations.AddField(
            model_name='allocationform',
            name='samester_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.samester'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequest_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.prerequest'),
        ),
        migrations.AddField(
            model_name='samester',
            name='program_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.program'),
            preserve_default=False,
        ),
    ]
