# Generated by Django 4.1.4 on 2022-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_allocationform_prerequest_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ManyToManyField(to='departments.teachers'),
        ),
    ]
