# Generated by Django 4.1.4 on 2022-12-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_course_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationform',
            name='student_strength',
        ),
        migrations.AlterField(
            model_name='allocationform',
            name='courses_ids',
            field=models.ManyToManyField(related_name='course', to='departments.course'),
        ),
        migrations.AlterField(
            model_name='allocationform',
            name='program_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
    ]
