# Generated by Django 4.1.4 on 2022-12-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_remove_allocationform_student_strength_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='samester_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='section',
        ),
        migrations.RemoveField(
            model_name='samester',
            name='student_strength',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('student_strength', models.IntegerField()),
                ('Samester_and_Sections_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.samester')),
            ],
        ),
        migrations.CreateModel(
            name='Samester_and_Section',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.program')),
                ('samester_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.samester')),
                ('sections_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.section')),
            ],
        ),
        migrations.CreateModel(
            name='course_and_teacher',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.course')),
                ('section_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.section')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.teachers')),
            ],
        ),
    ]
