# Generated by Django 4.1.4 on 2022-12-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_remove_course_samester_id_remove_course_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Labs',
            new_name='Lab',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
