# Generated by Django 4.1.4 on 2022-12-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_rename_departments_department_rename_labs_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Samester_and_Sections_id',
        ),
    ]
