# Generated by Django 4.1.4 on 2022-12-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_remove_section_samester_and_sections_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationform',
            name='department_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimeTable_Slot',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednseday'), ('Thursday', 'Thurdasy'), ('Firday', 'Friday')], default='Monday', max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.room')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('short_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departments.room')),
            ],
        ),
    ]
