# Generated by Django 4.1.4 on 2022-12-29 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_allocationform_department_id_timetable_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_slot',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='timetable_slot',
            name='room_id',
        ),
        migrations.AddField(
            model_name='timetable',
            name='lab_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable_slot',
            name='course_and_teacher_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.course_and_teacher'),
            preserve_default=False,
        ),
    ]
