# Generated by Django 4.1.4 on 2022-12-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_remove_timetable_slot_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationform',
            name='courses_ids',
            field=models.ManyToManyField(null=True, related_name='course', to='departments.course'),
        ),
        migrations.AlterField(
            model_name='allocationform',
            name='department_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='allocationform',
            name='program_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lab_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.lab'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.room'),
        ),
    ]
