# Generated by Django 4.1.4 on 2022-12-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_alter_allocationform_courses_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_slot',
            name='course_and_teacher_id',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='TimeTable_Slot',
        ),
    ]
