# Generated by Django 4.1.4 on 2023-01-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_remove_timetable_slot_course_and_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
