# Generated by Django 4.1.4 on 2023-01-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_alter_program_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samester_and_section',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.program'),
        ),
        migrations.AlterField(
            model_name='samester_and_section',
            name='samester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.samester'),
        ),
        migrations.AlterField(
            model_name='samester_and_section',
            name='sections_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.section'),
        ),
    ]
