# Generated by Django 4.1.4 on 2023-01-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_alter_samester_and_section_program_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.prerequest'),
        ),
        migrations.AlterField(
            model_name='course_and_teacher',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.course'),
        ),
        migrations.AlterField(
            model_name='course_and_teacher',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.section'),
        ),
        migrations.AlterField(
            model_name='course_and_teacher',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.teacher'),
        ),
    ]
