# Generated by Django 4.1.4 on 2023-01-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_alter_course_prerequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
