# Generated by Django 4.1.4 on 2023-01-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0017_alter_teacher_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.prerequest'),
        ),
    ]
