# Generated by Django 4.1.4 on 2023-01-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_alter_course_prerequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='allocationform',
            name='phone',
        ),
        migrations.AlterField(
            model_name='course_and_teacher',
            name='short_name',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
