# Generated by Django 4.1.4 on 2023-01-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_remove_allocationform_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationform',
            name='courses_ids',
            field=models.ManyToManyField(related_name='course', to='departments.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequest_id',
            field=models.ForeignKey(blank=True, help_text='only if course have pre request', null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.prerequest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(help_text=' courser Code It Must be unique', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
