# Generated by Django 4.1.4 on 2023-01-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_alter_allocationform_courses_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationform',
            name='samester_id',
        ),
        migrations.RemoveField(
            model_name='samester_and_section',
            name='samester_id',
        ),
        migrations.RemoveField(
            model_name='samester_and_section',
            name='sections_id',
        ),
        migrations.AddField(
            model_name='samester_and_section',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samester_and_section',
            name='samester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], default='1st', max_length=200),
        ),
        migrations.AddField(
            model_name='samester_and_section',
            name='sections',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=200),
        ),
        migrations.AddField(
            model_name='samester_and_section',
            name='student_strength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_and_teacher',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.samester_and_section'),
        ),
        migrations.DeleteModel(
            name='Samester',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
